---
abstract: 'optree statistics'
author:
  - 'Reini Urban <rurban@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: B-Stats
no_index:
  directory:
    - t
    - inc
requires:
  B: 0
  Opcodes: 0.10
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/rurban/B-Stats.git
version: 0.01_20111206
